# -*- coding: utf-8 -*-
"""TrabalhoDesempregoINPCIPCA (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WzJ3sfalsU3-bIul_SsJaxSR4KeIk390

Grupo: Flávio Melo, Adrielio Alvaro, Rodrigo Felix

**COMPARATIVO DA EFEITO DO DESEMPREGO NO INPC E NO IPCA**

---

1 - Importando funções necessárias
"""

#--- Bloco 1: Instalando e Importando Bibliotecas ---
#!pip install sidrapy -q  #Instalando por não fazer parte da biblioteca padrão

import streamlit as st
import sidrapy #Conveniencia para API do sidra
import pandas as pd
import numpy as np  #Suporte implicito a outras bibliotecas
import seaborn as sns #Gráfico de dispersão
import matplotlib.pyplot as plt #Gráficos geral
from scipy.stats import linregress #Para regressão linear
import warnings

#Suprime alertas de descontinuação do pandas
warnings.filterwarnings('ignore')

"""
2 - Coletar dados do Sidra
"""

#--- Bloco 2: Coletando os Dados do SIDRA (Últimos 120 meses) ---

#https://servicodados.ibge.gov.br/api/v3/agregados/7060/metadados para saber o que puxar
#IPCA - Variação acumulada em 12 meses - Brasil (Tabela 7060, Variável 2265)
raw_ipca = sidrapy.get_table(table_code="7060", territorial_level="1", ibge_territorial_code="all", variable="2265", period="last 120")

#INPC - Variação acumulada em 12 meses - Brasil (Tabela 7063, Variável 2292)
raw_inpc = sidrapy.get_table(table_code="7063", territorial_level="1", ibge_territorial_code="all", variable="2292", period="last 120")

#Desemprego - Trimestre Móvel (Taxa de Desocupação Total) - Brasil (Tabela 6381, Variável 4099)
raw_desemprego = sidrapy.get_table(table_code="6381", territorial_level="1", ibge_territorial_code="all", variable="4099", period="last 120")

"""3 - Tratando e alinhando os dados para criação do Framework"""

#--- Bloco 3: Framework de Tratamento e Alinhamento ---

def limpar_dados(df, nome_valor):  #No caso isso é criar a função que nesse bloco vai ser usada pra tratar a questão de cabeçalho dos três data frames trabalhados
    #Transforma a primeira linha em cabeçalho (metadados do SIDRA)
    df.columns = df.iloc[0]
    df = df[1:].reset_index(drop=True)

    #Identifica dinamicamente a coluna de tempo
    coluna_tempo = 'Mês (Código)' if 'Mês (Código)' in df.columns else 'Trimestre Móvel (Código)'  #é feio demais de ler os nomes que o SIDRA usa pra identificar isso

    #Mantém apenas a coluna de tempo e a coluna de Valor
    df = df[[coluna_tempo, 'Valor']].rename(columns={coluna_tempo: 'Data', 'Valor': nome_valor})

    #Converte valor para numérico e limpa nulos
    df[nome_valor] = pd.to_numeric(df[nome_valor].str.replace(',', '.'), errors='coerce') #errors='coerce' seria para, caso não consiga converter, considerar NaN
    df.dropna(subset=[nome_valor], inplace=True) #inplace=true tem a função de aplicar o dropna no df original, caso não houvesse o dropna criaria um novo df e retornaria ele

    #Converte a data para datetime
    df['Data'] = pd.to_datetime(df['Data'], format='%Y%m')  #Não consegui deixar fora do formato americano de data na formatação, aqui usamos pandas para organizar o formato da data no dataframe
    return df

#Limpando e combinando as bases usando a função criada no início do bloco(limpar_dados)
df_ipca = limpar_dados(raw_ipca, 'IPCA_12M')
df_inpc = limpar_dados(raw_inpc, 'INPC_12M')
df_desemprego = limpar_dados(raw_desemprego, 'Desemprego')

#Merge pela data
df_macro = df_ipca.merge(df_inpc, on='Data').merge(df_desemprego, on='Data')
df_macro.head()

"""4 - Calculando as Correlações"""

#--- Bloco 4: Análise e Correlações com Ajuste Econômico ---

#Organizando por data crescente, mantendo o número índice que indica a linha em posição
df_macro = df_macro.sort_values('Data').reset_index(drop=True)

#Cria a variação Anual do desemprego (Diferença entre hoje e 12 meses atrás)
df_macro['Var_Desemprego_12M'] = df_macro['Desemprego'].diff(12)

#Cria a defasagem de 3 meses do choque anualizado
df_macro['Var_Desem_12M_Lag3'] = df_macro['Var_Desemprego_12M'].shift(3)

#Purificação central da amostra: remove os NaNs gerados pelo diff e shift
#Isso garante que correlação, gráficos e regressão usem exatamente a mesma janela de dados
df_clean = df_macro.dropna(subset=['Var_Desem_12M_Lag3', 'IPCA_12M', 'INPC_12M']).copy()  #.copy() para garantir o problema visto em sala 'SettingWithCopyWarning'

print("="*70)
print("CORRELAÇÃO: Choque Anual de Desemprego (Defasado 3m) vs Inflação 12m")
print("="*70)

matriz_corr = df_clean[['Var_Desem_12M_Lag3', 'IPCA_12M', 'INPC_12M']].corr() #.corr() é fazer uma correlação entre os valores
print(matriz_corr.loc[['IPCA_12M', 'INPC_12M'], ['Var_Desem_12M_Lag3']])
print("\n-> Interpretação  : Valores negativos indicam que aumentos anuais de desemprego reduzem a inflação acumulada do período. \n-> Interpretação 2: INPC apresenta maior correlação com desemprego.")

"""5 - visualizando diferença de impacto"""

#--- Bloco 5: Visualização dos Efeitos Defasados na Inflação ---

plt.figure(figsize=(12, 5)) #tamanho do gráfico

#Pegando datas de forma dinâmica para os títulos a partir do df_clean
data_ini = df_clean['Data'].min().strftime('%b/%Y') #Salvando o menor valor de data e transformando em strftime(tempo em forma de string %b abeviação do mes %Y ano com 4 dígitos)
data_fim = df_clean['Data'].max().strftime('%b/%Y') #...
titulo_periodo = f"({data_ini} a {data_fim})"

#Gráfico para o IPCA
plt.subplot(1, 2, 1)  #1 linha, 2 colunas, posição 1
sns.regplot(data=df_clean, x='Var_Desem_12M_Lag3', y='IPCA_12M', color='blue', scatter_kws={'alpha':0.5}) #usado para gráfico de dispersão
plt.title(f'Impacto do Choque Anual de Desemprego no IPCA\n{titulo_periodo}', fontsize=11)
plt.xlabel('Variação do Desemprego há 3 meses (Acumulado 12M em p.p.)')
plt.ylabel('IPCA (Acumulado 12 meses, %)')

#Gráfico para o INPC
plt.subplot(1, 2, 2)  #1 linha, 2 colunas, posição 2
sns.regplot(data=df_clean, x='Var_Desem_12M_Lag3', y='INPC_12M', color='orange', scatter_kws={'alpha':0.5})
plt.title(f'Impacto do Choque Anual de Desemprego no INPC\n{titulo_periodo}', fontsize=11)
plt.xlabel('Variação do Desemprego há 3 meses (Acumulado 12M em p.p.)')
plt.ylabel('INPC (Acumulado 12 meses, %)')

plt.tight_layout() #ajuste do espaçamento entre os gráficos
plt.show()

#---------------------------------------------------------------------------
#Gráfico de Linhas para as Três Variáveis do Modelo
#---------------------------------------------------------------------------
plt.figure(figsize=(14, 6))

# Plotando as linhas correspondentes a cada variável
plt.plot(df_clean['Data'], df_clean['IPCA_12M'], label='IPCA (Acum. 12M)', color='blue', linewidth=2)
plt.plot(df_clean['Data'], df_clean['INPC_12M'], label='INPC (Acum. 12M)', color='orange', linewidth=2)
plt.plot(df_clean['Data'], df_clean['Desemprego'], label='Taxa de Desemprego', color='green', linewidth=2, linestyle='--')

# Configurações estéticas do gráfico de linhas
plt.title(f'Evolução Temporal do IPCA, INPC e Taxa de Desemprego\n{titulo_periodo}', fontsize=13, fontweight='bold')
plt.xlabel('Linha do Tempo (Data)', fontsize=11)
plt.ylabel('Percentual (%)', fontsize=11)
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend(loc='upper right', fontsize=10, frameon=True)

plt.tight_layout()
plt.show()

"""6 - Análise de Elasticidade (Regressão Linear) / conclusão"""

#--- Bloco 6: Regressão Linear com Alta Precisão ---


#Y(reta da correlação var_desemprego e inflação)=α(intercept/constante)+β(slope/coeficiente da reta)X
#r = coeficiente de correlação, p = teste da hipotese(quanto maior P, mais ligados são as variáveis)
#Cálculo IPCA
slope_ipca, _, r_ipca, p_ipca, _ = linregress(df_clean['Var_Desem_12M_Lag3'], df_clean['IPCA_12M'])

#Cálculo INPC
slope_inpc, _, r_inpc, p_inpc, _ = linregress(df_clean['Var_Desem_12M_Lag3'], df_clean['INPC_12M'])

#Calculo da diferença percentual do efeito nos dois índices
dif_perc = ((abs(slope_inpc) - abs(slope_ipca)) / abs(slope_ipca)) * 100

print("ANÁLISE DE SENSIBILIDADE (JANELA ANUALIZADA)")
print("-"*60)
print(f"Elasticidade no IPCA: {slope_ipca:.4f} (R²: {r_ipca**2:.4f}, p-valor: {p_ipca:.4f})")
print(f"Elasticidade no INPC: {slope_inpc:.4f} (R²: {r_inpc**2:.4f}, p-valor: {p_inpc:.4f})")
print("-" * 60)
print(f"Diferença do impacto sobre os índices (Absoluto): {abs(slope_ipca - slope_inpc):.4f}")
print("\nCONCLUSÃO:")

if abs(slope_inpc) > abs(slope_ipca):
    print("O INPC apresentou maior sensibilidade às variações do desemprego do que o IPCA.")
    dif_perc = ((abs(slope_inpc) - abs(slope_ipca)) / abs(slope_ipca)) * 100
    print(f"O INPC apresentou sensibilidade {dif_perc:.1f}% superior à do IPCA.")
elif abs(slope_ipca) > abs(slope_inpc):
    print("O IPCA apresentou maior sensibilidade às variações do desemprego do que o INPC.")
    dif_perc = ((abs(slope_ipca) - abs(slope_inpc)) / abs(slope_inpc)) * 100
    print(f"O IPCA apresentou sensibilidade {dif_perc:.1f}% superior à do INPA.")
else:
    print("Ambos apresentaram a mesma sensibilidade a variação da taxa de desemprego.")

